let compass = 0
function E () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(0, 2)
    led.plot(0, 3)
    led.plot(0, 4)
    led.plot(1, 0)
    led.plot(1, 2)
    led.plot(1, 4)
    led.plot(2, 0)
    led.plot(2, 2)
    led.plot(2, 4)
    led.plot(3, 0)
    led.plot(3, 4)
}
input.onButtonPressed(Button.A, function () {
    input.calibrateCompass()
})
function N () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(0, 2)
    led.plot(0, 3)
    led.plot(0, 4)
    led.plot(1, 1)
    led.plot(2, 2)
    led.plot(3, 3)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(4, 2)
    led.plot(4, 3)
    led.plot(4, 4)
}
function S () {
    led.plot(0, 1)
    led.plot(0, 4)
    led.plot(1, 0)
    led.plot(1, 2)
    led.plot(1, 4)
    led.plot(2, 0)
    led.plot(2, 2)
    led.plot(2, 4)
    led.plot(3, 0)
    led.plot(3, 3)
}
function W () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(0, 2)
    led.plot(0, 3)
    led.plot(0, 4)
    led.plot(1, 3)
    led.plot(2, 2)
    led.plot(3, 3)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(4, 2)
    led.plot(4, 3)
    led.plot(4, 4)
}
basic.forever(function () {
    compass = input.compassHeading()
    if (compass >= 340 || compass <= 20) {
        basic.clearScreen()
        S()
        TobbieII.forward()
        basic.pause(1000)
        TobbieII.stopwalk()
    } else if (compass >= 21 && compass <= 120) {
        music.playTone(262, music.beat(BeatFraction.Eighth))
        basic.clearScreen()
        W()
        TobbieII.leftward()
        basic.pause(100)
        TobbieII.stopturn()
    } else if (compass >= 211 && compass <= 339) {
        music.playTone(262, music.beat(BeatFraction.Eighth))
        basic.clearScreen()
        E()
        TobbieII.rightward()
        basic.pause(100)
        TobbieII.stopturn()
    } else if (compass >= 110 && compass <= 210) {
        music.playTone(262, music.beat(BeatFraction.Eighth))
        basic.clearScreen()
        N()
        TobbieII.rightward()
        basic.pause(150)
        TobbieII.stopturn()
    }
})
